version: '3.8'
services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - my_pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:pass@postgres/db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  my_pgdata: